{"cells":[{"cell_type":"markdown","metadata":{"id":"BUZH2533wuuq"},"source":["# **Introducción a Python**\n","# FP25. Manejo de errores y excepciones"]},{"cell_type":"markdown","metadata":{"id":"CXOHoI0rwuut"},"source":["¡Incluso los agentes especiales cometen errores! Definitivamente has cometido errores hasta este punto de tu entrenamiento. Veamos qué se produce cuando obtenemos un error e intentemos comprenderlos mejor:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"9wsl8Ecrwuuu"},"outputs":[],"source":["# Ejecuta esta celda tal y como está ...\n","\n","print('hola)"]},{"cell_type":"markdown","metadata":{"id":"c4cwxjb9wuuv"},"source":["Fíjate que obtenemos un **SyntaxError**, con la descripción adicional de que fue un **EOL (Error de fin de línea) mientras se escanea la cadena literal**. Esto es lo suficientemente específico para que veamos que olvidamos una comilla simple al final de la línea. Comprender estos diversos tipos de errores te ayudarán a depurar tu código mucho más rápido.\n","\n","Este tipo de error y descripción se conoce como una **Excepción** (*Exception*). Incluso si una declaración o expresión es sintácticamente correcta, puede causar un error cuando se intenta ejecutarla. Los errores detectados durante la ejecución se denominan excepciones y no son necesariamente fatales.\n","\n","Puedes consultar la lista completa de [excepciones](https://docs.python.org/3/tutorial/errors.html) aquí. Ahora aprendamos a manejar errores y excepciones en nuestro propio código."]},{"cell_type":"markdown","metadata":{"id":"vLTI3Hcnwuuw"},"source":["## <font color='blue'>**La sentencia `try` `except`**</font>\n","\n","La terminología y la sintaxis básicas que se utilizan para manejar errores en Python son las declaraciones `try` y `except`. El código que puede hacer que ocurra una excepción se coloca en el bloque `try` y el manejo de la excepción se implementa en el bloque de código `except`. Nuevamente la indentación es clave en esta estructura. La forma de sintaxis es:\n","```python\n","     try:\n","        # Intentas tu operación aquí\n","     except ExceptionI:\n","        # Si hay ExceptionI, ejecuta este bloque.\n","     except ExceptionII:\n","        # Si hay ExceptionII, ejecuta este bloque.\n","     else:\n","        # Si no hay excepción, ejecuta este bloque.\n","     finally:\n","        # Siempre ejecuta este código\n","```\n","También podemos verificar cualquier excepción con solo usar `except`. Para comprender mejor todo esto, veremos un ejemplo de un código que abre y escribe en un archivo."]},{"cell_type":"markdown","metadata":{"id":"-NjkE3OAwuuw"},"source":["<font color='red'>Atención:</font>\n","\n","La siguiente línea de código creará un archivo en modo escritura en el directorio en el cual este notebook se está ejecutando."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"hoMxCJBiwuux"},"outputs":[],"source":["try:\n","    f = open('testfile','w')\n","    f.write('Prueba escribiendo esto')\n","\n","except IOError:\n","\n","    # Esto solo buscará una excepción del tipo IOError y luego ejecutará la declaración de print( )\n","    print(\"Error: Archivo no encontrado o no se pudo leer su data\")\n","else:\n","\n","    print(\"Contenido escrito exitosamente\")\n","    f.close()"]},{"cell_type":"markdown","metadata":{"id":"niDeY-Ttwuuy"},"source":["Ahora veamos qué pasaría si no tuviéramos permiso de escritura (abriendo solo con 'r'):"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"5eam3xn-wuuy"},"outputs":[],"source":["try:\n","    f = open('testfile','r')\n","    f.write('Prueba escribiendo esto')\n","\n","except IOError:\n","\n","    # Esto solo buscará una excepción del tipo IOError y luego ejecutará la declaración de print( )\n","    print(\"Error: Archivo no encontrado o no se pudo leer su data\")\n","else:\n","\n","    print(\"Contenido escrito exitosamente\")\n","    f.close()"]},{"cell_type":"markdown","metadata":{"id":"lh_uCCzAwuuz"},"source":["Si queremos verificar varios errores, podemos usar sólo `except:`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"uTkb6VRWwuuz"},"outputs":[],"source":["try:\n","    f = open('testfile','r')\n","    f.write('Prueba escribiendo esto')\n","\n","except:\n","\n","    # En este caso se evaluarán todas las posibles excepciones\n","    print(\"Error: Archivo no encontrado o no se pudo leer su data\")\n","else:\n","\n","    print(\"Contenido escrito exitosamente\")\n","    f.close()"]},{"cell_type":"markdown","metadata":{"id":"S7BzbrBFwuuz"},"source":["De esta manera, no tendrás que preocuparte por memorizar todos los tipos de excepción posibles.\n","\n","## <font color='blue'>**La cláusula `finally`**</font>\n","Veamos ahora la palabra clave `finally`:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"DCtLOiAuwuu0"},"outputs":[],"source":["try:\n","    f = open(\"testfile\", \"w\")\n","    f.write(\"Prueba escribiendo esto\")\n","finally:\n","    print(\"Siempre se ejecuta el set de instrucciones anidadas en 'finally'\")\n","    f.close()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"yeOaMz8zwuu0"},"outputs":[],"source":["try:\n","\n","    f = open(\"testfile\", \"r\")\n","    f.write(\"Prueba escribiendo esto\")\n","finally:\n","    print(\"Siempre se ejecuta el set de instrucciones anidadas en 'finally'\")"]},{"cell_type":"markdown","metadata":{"id":"6nq40ZDcwuu0"},"source":["Podemos usar esto junto con la palabra clave `except`; con ello obtenemos una estructura de manejo de errores del tipo: `try`, `except`, `else` y `finally`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"d3Gjq2IZwuu0"},"outputs":[],"source":["try:\n","    f = open('testfile','r')\n","    f.write('Prueba escribiendo esto')\n","\n","except:\n","\n","    # En este caso se evaluarán todas las posibles excepciones\n","    print(\"Error: Archivo no encontrado o no se pudo leer su data\")\n","else:\n","\n","    print(\"Contenido escrito exitosamente\")\n","\n","finally:\n","    f.close()\n","    print('Siempre se ejecuta el set de instrucciones anidadas en \"finally\"')"]},{"cell_type":"markdown","metadata":{"id":"SSL9PW0Ywuu1"},"source":["## <font color='blue'>**La palabra clave `raise`**</font>\n","En Python, se generan excepciones cuando se producen errores en tiempo de ejecución. También podemos generar excepciones manualmente usando la palabra clave `raise`.\n","\n","Opcionalmente, podemos pasar valores a la excepción para aclarar por qué se generó esa excepción.\n","\n","La sintáxis completa es la siguiente:\n","```python\n","raise NombreError('Mensaje de error (opcional)')  # Con mensaje de error\n","\n","raise NombreError                                 # Si mensaje de error\n","```\n","Veamos un par de ejemplos"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"jXVnNxBrwuu1"},"outputs":[],"source":["# Genera una excepción si el valor es menor a cero\n","x = -1\n","if x <= 0:\n","    raise Exception('Sólo números mayores a cero')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"6xpknXTgwuu1"},"outputs":[],"source":["# Ingresar un año\n","\n","def isBisiesto(year):\n","    if year.isnumeric():\n","        print('Calcula año bisiento')\n","    else:\n","        raise TypeError('Solo ingresar números enteros')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"6aRF58puwuu1"},"outputs":[],"source":["isBisiesto('2021')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"MRpP8b1lwuu2"},"outputs":[],"source":["isBisiesto('hola')"]},{"cell_type":"markdown","metadata":{"id":"pWmtRKHJwuu2"},"source":["Veamos lo mismo con `try`, `except`"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C0HjIsolwuu2"},"outputs":[],"source":["def isBisiesto2(year):\n","    try:\n","        int(year)\n","\n","    except ValueError:\n","        raise TypeError('Solo ingresar números enteros')\n","\n","    else:\n","        print('Calcula año bisiento')\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FlNNBZ8Wwuu2"},"outputs":[],"source":["isBisiesto2('1998')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TLTn9jWZwuu2"},"outputs":[],"source":["isBisiesto2('hola')"]},{"cell_type":"markdown","source":["## <font color='blue'>__Ejercicios__</font>"],"metadata":{"id":"pXeh9WolSLIA"}},{"cell_type":"markdown","metadata":{"id":"56KW-_sewuu2"},"source":["### <font color='green'>Actividad 1: Challenging</font>\n","### Mejora tu función para el algoritmo del año bisiesto del notebook FP18\n","\n","Toma función que realizaste en el notebook FP18 y mejórala con lo siguiente:\n","\n","* Utiliza `try`, `except`, `else` para controlar errores\n","* Utiliza `raise` para generar excepciones\n","* Prueba isBisiesto3()\n","\n","Nombra tu función **isBisiesto3()**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"DjditIq3wuu2"},"outputs":[],"source":["# Tu código aquí ...\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"W1WxfZziwuu3"},"outputs":[],"source":["isBisiesto3('2018')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"F8Od1tE_wuu3"},"outputs":[],"source":["isBisiesto3('2020')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"2wlldjiDwuu3"},"outputs":[],"source":["isBisiesto3('hola')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ZShQq7e8wuu3"},"outputs":[],"source":["isBisiesto3('2018.0')"]},{"cell_type":"markdown","metadata":{"id":"frQjbvRCwuu3"},"source":["<font color='green'>Fin actividad 1</font>"]},{"cell_type":"markdown","source":["<img src=\"https://drive.google.com/uc?export=view&id=1DNuGbS1i-9it4Nyr3ZMncQz9cRhs2eJr\" width=\"100\" align=\"left\" title=\"Runa-perth\">\n","<br clear=\"left\">\n","\n","## <font color='blue'>**Resumen**</font>\n","La cláusula `try` en Python se utiliza para atrapar y manejar excepciones. Las excepciones son errores que ocurren durante la ejecución del programa. Cuando ocurre una excepción en el código, el flujo normal del programa se interrumpe. Si la excepción no se maneja, el programa se detendrá y mostrará un mensaje de error.\n","\n","Aquí es donde entra en juego la cláusula `try`. Puedes poner el código que podría generar una excepción dentro de un bloque `try`. Si ocurre una excepción en el bloque try, el flujo del programa se pasa a un bloque `except` correspondiente, donde se puede manejar la excepción.\n","\n","Además, la declaración `try` puede tener una cláusula `else`. El código dentro del bloque `else` se ejecuta si el código dentro del bloque `try` no generó ninguna excepción.\n","\n","Finalmente, la cláusula `finally` es opcional y se puede agregar después de los bloques `try` y `except`. El código dentro del bloque `finally` se ejecuta sin importar si se produjo una excepción o no. Es útil para acciones de limpieza que deben ser ejecutadas independientemente de si ocurrió un error.\n","\n","Aquí tienes un ejemplo:\n","\n","```python\n","try:\n","    # Código que podría generar una excepción\n","    resultado = 10 / 0\n","except ZeroDivisionError:\n","    # Esto se ejecuta si hay una excepción ZeroDivisionError\n","    print(\"Ha ocurrido una división por cero.\")\n","else:\n","    # Esto se ejecuta si no hay excepciones\n","    print(\"La división se realizó con éxito.\")\n","finally:\n","    # Esto se ejecuta sin importar si hay una excepción o no\n","    print(\"Esto se imprime siempre.\")\n","\n","```\n","En este ejemplo, la división por cero genera una excepción `ZeroDivisionError`, por lo que el bloque `except` se ejecuta. Luego, sin importar si se produjo una excepción o no, el bloque `finally` también se ejecuta.\n","\n","<img src=\"https://drive.google.com/uc?export=view&id=1DNuGbS1i-9it4Nyr3ZMncQz9cRhs2eJr\" width=\"50\" align=\"left\" title=\"Runa-perth\">\n","<br clear=\"left\">"],"metadata":{"id":"5J_-4m0NSzBl"}},{"cell_type":"markdown","metadata":{"id":"YqhW9kDJwuu3"},"source":["Muy bien hecho!!"]}],"metadata":{"anaconda-cloud":{},"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.11"},"colab":{"provenance":[],"toc_visible":true}},"nbformat":4,"nbformat_minor":0}